config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :racers
  resources :calendar_of_the_championships
  resources :racers
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

end

app/models/racer.rb
class Racer < ActiveRecord::Base
  has_many :teams1, class_name: 'Team', foreign_key: 'racer1_id'
  has_many :teams2, class_name: 'Team', foreign_key: 'racer2_id'

  validates :surname, :firstname, :bday, :country, :number_of_wins, presence: true

end

app/controllers/racers_controller.rb
class RacersController < ApplicationController
  before_action :set_racer, only: [:show, :edit, :update, :destroy]

  # GET /racers
  # GET /racers.json
  def index
    @racers = Racer.all
  end

  # GET /racers/1
  # GET /racers/1.json
  def show
  end

  # GET /racers/new
  def new
    @racer = Racer.new
  end

  # GET /racers/1/edit
  def edit
  end

  # POST /racers
  # POST /racers.json
  def create
    @racer = Racer.new(racer_params)

    respond_to do |format|
      if @racer.save
        format.html { redirect_to @racer, notice: 'Racer was successfully created.' }
        format.json { render :show, status: :created, location: @racer }
      else
        format.html { render :new }
        format.json { render json: @racer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /racers/1
  # PATCH/PUT /racers/1.json
  def update
    respond_to do |format|
      if @racer.update(racer_params)
        format.html { redirect_to @racer, notice: 'Racer was successfully updated.' }
        format.json { render :show, status: :ok, location: @racer }
      else
        format.html { render :edit }
        format.json { render json: @racer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /racers/1
  # DELETE /racers/1.json
  def destroy
    @racer.destroy
    respond_to do |format|
      format.html { redirect_to racers_url, notice: 'Racer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_racer
      @racer = Racer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def racer_params
      params.require(:racer).permit(:surname, :firstname, :bday, :country, :number_of_wins)
    end
end

app/helpers/racers_helper.rb
module RacersHelper
end

app/views/racers/_form.html.haml
= form_for @racer do |f|
  - if @racer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@racer.errors.count, "")}неправильно заполненных полей:"
      %ul
        - @racer.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :surname, "Фамилия"
    = f.text_field :surname
  .field
    = f.label :firstname, 'Имя'
    = f.text_field :firstname
  .field
    = f.label :bday, 'Дата рождения'
    = f.date_select :bday
  .field
    = f.label :country, 'Страна'
    = f.text_field :country
  .field
    = f.label :number_of_wins,'Количество побед'
    = f.number_field :number_of_wins
  .actions
    = f.submit 'Сохранить'

app/views/racers/edit.html.haml
%h1 Редактировать

= render 'form'

= link_to 'Посмотреть', @racer
\|
= link_to 'Назад', racers_path

app/views/racers/index.html.haml
%h1 Список гонщиков

%table
  %thead
    %tr
      %th Фамилия
      %th Имя
      %th Дата рождения
      %th Страна
      %th Количество побед
      %th
      %th
      %th

  %tbody
    - @racers.each do |racer|
      %tr
        %td= racer.surname
        %td= racer.firstname
        %td= racer.bday
        %td= racer.country
        %td= racer.number_of_wins
        %td= link_to 'Показать', racer
        %td= link_to 'Редактировать', edit_racer_path(racer)
        %td= link_to 'Удалить', racer, :method => :delete, :data => { :confirm => 'Вы уверены?' }

%br

= link_to 'Новый гонщик', new_racer_path

app/views/racers/new.html.haml
%h1 Новый гонщик

= render 'form'

= link_to 'Назад', racers_path

app/views/racers/show.html.haml
%p#notice= notice

%p
  %b Surname:
  = @racer.surname
%p
  %b Firstname:
  = @racer.firstname
%p
  %b Bday:
  = @racer.bday
%p
  %b Country:
  = @racer.country
%p
  %b Number of wins:
  = @racer.number_of_wins

= link_to 'Редактировать', edit_racer_path(@racer)
\|
= link_to 'Назад', racers_path