config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :racers
  resources :calendar_of_the_championships
  resources :racers
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :require_login
  before_action :check_app_auth

  private
  ## Выбор текущей роли и проверка прав доступа для неё у данного пользователя
  def check_app_auth()
    if current_user.nil?
      redirect_to(login_path(), notice: flash[:notice])
    else
      @current_user_object = current_user
      @current_user_login = @current_user_object.email
      
      @current_role_user = params[:user_role_id]
      @current_role_user = session[:user_role_id] if @current_role_user.nil?
      if @current_role_user.nil?
        @current_role_user = @current_user_object.role_users.first
      else
        @current_role_user = RoleUser.find(@current_role_user)
        unless @current_user_object.role_users.include?(@current_role_user)
          @current_role_user = @current_user_object.role_users.first
        end
      end
      # Сохраняем в сессию, чтобы данная роль была выбрана и дальше
      unless @current_role_user.nil?
        session[:user_role_id] = @current_role_user.id
      end  
      unless check_ctr_auth()
        redirect_to(ip_path(
          :bad_action_name => action_name,
          :bad_controller_name => controller_name,
          :bad_user_role => @current_role_user.try(:id)))
      end
    end
  end

  ## Проверка прав доступа выбранной роли для данного метода
  def check_ctr_auth()
    return @current_role_user.try(:is_admin?)
  end

  def not_authenticated
    redirect_to login_path, danger: "Сначала войдите в систему!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def lnil(date)
    date.nil? ? 'не указано' : l(date)
  end
  
  def breadcrumb_tag(&block)
    render 'application/breadcrumb', block: capture(&block)
  end
end

app/views/application/_breadcrumb.html.haml
-content_for :breadcrumb do
  %ul.breadcrumb.hidden-print
    = block

app/views/application/_error_messages_for.html.haml
-if object.errors.present?
  .alert.alert-danger
    %h4 При сохранении произошли ошибки
    %ul
      -object.errors.full_messages.each do |msg|
        %li=msg

app/views/application/_error_messages_for_attr.html.haml
-if object.errors[attr].present?
  .text-danger
    %ul.list-unstyled
      -object.errors.delete(attr).each do |msg|
        %li=msg

app/views/application/_flash_messages.html.haml
-flash.each do |key,val|
  .growl-msg{data: {type: key.to_s=='notice' ? 'success' : key}}=val

app/views/application/_navbar_top.html.haml
%nav.navbar.navbar-inverse.hidden-print#top-bar
  .container-fluid
    .navbar-header
      .navbar-brand
        = link_to root_path do
          = image_tag 'logo.png', alt: t('app.company.short_name')
          = t('app.name')
        = link_to '|Гонщики |', racers_path
        = link_to '|Календарь чемпионата |', calendar_of_the_championships_path
        = link_to '|Состав команд |', teams_path


      %button.navbar-toggle.collapsed{type: 'button', data: {toggle: 'collapse', target: '#bs-example-navbar-collapse-1'}}
        %span.sr-only
          Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    %ul.nav.navbar-nav.navbar-right.collapse.navbar-collapse#bs-example-navbar-collapse-1
      %li
        = link_to login_path do
          = @current_user.blank? ? 'войти' : @current_user.email
      %li
        - if @current_user.blank?
          = link_to login_path do
            = fa_icon 'sign-in'
        - else
          = link_to logout_path do
            = fa_icon 'sign-out'

app/views/application/_sidebar.html.haml
%aside.hidden-print#sidebar-wrapper
  %ul.sidebar-nav
    - side_bar_items(@current_role_user).each do |item|
      %li
        - if item.has_key?(:children)
          = link_to('#', class: 'with-subitems') do
            = fa_icon(item[:icon], class: 'menu-icon')
            = item[:name]
            %span.pull-right.carret
              = fa_icon('angle-down', class: 'menu-icon')              
          %ul.subitems{class: (item[:children].any?{ |subitem| is_open?(subitem[:controller], subitem[:action]) } ? :subopen : :subclose)}
            - item[:children].each do |subitem|
              %li.subitem
                - if subitem.has_key?(:params)
                  = link_to(url_for({controller: subitem[:controller], action: subitem[:action]}.merge(subitem[:params])), class: subitem[:class]) do        
                    = fa_icon(subitem[:icon], class: 'menu-icon')
                    = subitem[:name]
                - else
                  = link_to(url_for(controller: subitem[:controller], action: subitem[:action]), class: subitem[:class]) do        
                    = fa_icon(subitem[:icon], class: 'menu-icon')
                    = subitem[:name]
        - else
          = link_to(url_for(controller: item[:controller], action: item[:action]), class: item[:class]) do
            = fa_icon(item[:icon], class: 'menu-icon')
            = item[:name]
    %li.footer
      %div
        © В.Ю. Радыгин

app/views/application/access_denied.html.haml
%h1
  Доступ запрещён!

.alert.alert-danger
  Пользователю 
  = @current_user.nil? ? 'не авторизован' : @current_user.email
  к действию
  = action_name
  контроллера
  = controller_name
  доступ запрещён!  

= link_to 'Назад', login_path

app/views/application/error.html.haml
.alert.alert-danger=@error